loan = read.csv("loans.csv")
table(loan$not.fully.paid)
1533/(1533+8045)
summary(loan)
install.packages("mice")
library(mice)
vars.for.imputation = setdiff(names(loan),"not.fully.paid")
imputed= complete(mice(loan[vars.for.imputation]))
loan[vars.for.imputation]=imputed
set.seed(144)
library(caTools)
loans=read.csv("loans_imputed.csv")
split = sample.split(loans$not.fully.paid,SplitRatio = 0.7)
train = subset(loans, split==TRUE)
test = subset(loans, split==FALSE)
model = glm(not.fully.paid~.,data=train,family = binomial)
summary(model)
pred= predict(model,newdata = test,type ="response")
table(test$not.fully.paid,pred>0.5)
(2400+3)/(2400+3+457+13)
table(train$not.fully.paid)
5632/(5632+1073)
library(ROCR)
rocrpred= prediction(pred,test$not.fully.paid)
as.numeric(performance(rocrpred,"auc")@y.values)
model1=glm(not.fully.paid~int.rate,data=train,family = binomial)
summary(model1)
pred1=predict(model1,newdata = test,type = "response")
summary(pred1))
table(test$not.fully.paid,pred1>0.5)
table(test$not.fully.paid)
rocrpred1=prediction(pred1,test$not.fully.paid)
auc=as.numeric(performance(rocrpred1,"auc")@y.values)
test$profit= exp(test$int.rate*3)-1
test$profit[test$not.fully.paid==1]=-1
summary(test$profit)
0.8895*10
high = subset(test,test$int.rate>=.15)
summary(high$profit)
table(high$not.fully.paid)
110/(110+327)
cutoff = sort(high$p)

