rm(list=ls())
parole = read.csv("parole.csv")
table(parole$crime)
str(parole)
summary(parole)
parole$state = as.factor(parole$state)
parole$crime = as.factor(parole$crime)
summary(parole)
set.seed(144)
library(caTools)
split=sample.split(parole$violator,SplitRatio = 0.7)
train=subset(parole,split==TRUE)
test=subset(parole,split==FALSE)
model = glm(violator~.,data=train,family ="binomial")
summary(model)
pred= predict(model,newdata = test,type = "response")
summary(pred)
table(test$violator,pred>0.5)
table(train$violator)
418/(418+55)
library(ROCR)
rocrpred= prediction(pred,test$violator)
as.numeric(performance(rocrpred,"auc")@y.values)
